name: nestm-shopify

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v3
      - name: install and build
        run: npm ci
      - name: publish to registry
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@conspireagency"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
